name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install clojure
        uses: DeLaGuardo/setup-clojure@3.1
        with:
          tools-deps: 1.10.1.492
      - name: Run test
        run: clojure -A:test
